=begin
#Brainrex API Explorer

#Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)

OpenAPI spec version: 0.1.1
Contact: support@brainrex.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BlockchainApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BlockchainApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BlockchainApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlockchainApi' do
    it 'should create an instance of BlockchainApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BlockchainApi)
    end
  end

  # unit tests for blockchain_average_tx
  # Calculate average transccion fee of a given blockchain
  # Calculates the average trasnsaction fee of a given 
  # @param request Name of the blockchain and date range.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse201]
  describe 'blockchain_average_tx test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for blockchain_list
  # The blockchains data structure supported by the Brainrex API
  # List of supported blockchains networks for analysis. The full history of the networks are available.
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'blockchain_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
